<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageReference Include="NSubstitute" Version="6.2.0" />
    <PackageReference Include="Testcontainers.Redis" Version="4.15.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Pdsr.Cache.Redis\Pdsr.Cache.Redis.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\Shared\*.cs" LinkBase="Shared" />
  </ItemGroup>
</Project>
