name: .NET

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  CI: 'true'
  DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: signing key
      run: echo ${{ secrets.SNKEY }} | base64 -d > key.snk
    - name: Build
      run: dotnet build --configuration Release -p:SignAssembly=True --no-restore
    - name: Make packages
      run: |
        dotnet pack --no-build --no-restore --configuration Release --output ./artifacts/ src/Pdsr.Cache
        dotnet pack --no-build --no-restore --configuration Release --output ./artifacts/ src/Pdsr.Cache.InMemory
        dotnet pack --no-build --no-restore --configuration Release --output ./artifacts/ src/Pdsr.Cache.NoCache
        dotnet pack --no-build --no-restore --configuration Release --output ./artifacts/ src/Pdsr.Cache.Polly
        dotnet pack --no-build --no-restore --configuration Release --output ./artifacts/ src/Pdsr.Cache.Redis
        dotnet pack --no-build --no-restore --configuration Release --output ./artifacts/ src/Pdsr.Cache.SqlServer

    - name: Upload package artifacts
      uses: actions/upload-artifact@v3
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      with:
        name: nuget-packages
        path: |
          **/*.nupkg
          **/*.snupkg
          - name: Publish packages
        run: |
          dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }}
