name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CI: 'true'
  DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: signing key
      run: echo ${{ secrets.SNKEY }} | base64 -d > key.snk
    - name: Get current version
      run: |
        dotnet tool install --global Nito.ProjProps
        echo "NEWTAG=v$(projprops --project src/Directory.Build.props)" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Release -p:SignAssembly=True --no-restore
    - name: Make packages
      run: dotnet pack --no-build --no-restore --configuration Release --output ./artifacts/
    - name: Upload package artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nuget-packages
        path: |
          **/*.nupkg
          **/*.snupkg
    - name: Publish packages
      if: env.NEWTAG != steps.existingtag.outputs.tag
      run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }}
